name: Build executables
on:
  push:
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Installation de PyInstaller
        run: pip install pyinstaller

      - name: Création de l'exécutable
        run: pyinstaller --onefile main.py

      - name: Renommage de l'exécutable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/main.exe dist/horaire-papier-win.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/main dist/horaire-papier-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/main dist/horaire-papier-macos
          fi
        shell: bash

      - name: Téléversement de l'artéfact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: dist/*
