name: Déploiement du README comme page Github

on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Génère le HTML
        run: |
          npm install -g showdown
          showdown makehtml -i README.md -o README.html

      - name: Triage du fichiers
        run: mkdir -p dist && mv index.html dist/

      - name: Configuration de Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "."
      - name: Déploiement vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
